- hosts: all
  become: true
  become_user: ubuntu
  become_method: su
  become_flags: '--login'
  tasks:
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yaml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yaml
